### ISSUE TITLE
$DiskLayout -eq 'BIOS'

### ISSUE THREAD

**Issue by d0rdmid0nt** [BladeFireLight/WindowsImageTools#4]
In Private/Set-DiskPartition.ps1:
`
if ($DiskLayout -eq 'BIOS')
Run-Executable -Executable "$windir\System32\bcdboot.exe"
`
is wrong, it should be bcdedit.exe

**Comment by BladeFireLight** [comment]
bcdboot is commonly used when imageing it's simple for creating new BCD entries. 

is there a specific scenario where this did not work for you?
