### ISSUE TITLE
Module export for New-Unattended does not match function New-UnattendXml

### ISSUE THREAD

**Issue by drstonephd** [BladeFireLight/WindowsImageTools#7]
The function New-UnattendXml is not public.  
## Expected Behavior

I should be able to execute either New-UnattendXml or New-Unattend
## Current Behavior

New-UnattendXml is not available.
## Possible Solution

Rename the function from New-UnattendXml to New-Unattended.  Or rename the file from New-Unattend to New-UnattendXml and update the FunctionToExport for the new name.  
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I'm going to try to automatically set the computer name, administrator password, and partition letters for extra drives.  I will also try to add my domain account as local admin and add the VM to the domain.  
## Your Environment

* Module version used:
* Operating System and PowerShell version:

**Comment by BladeFireLight** [comment]
thanks for pointing this out. I did not test that in my hurry to update everything to use Stucko
