### ISSUE TITLE
Simplified timezone and language validation?  

### ISSUE THREAD

**Issue by drstonephd** [BladeFireLight/WindowsImageTools#9]
Noticed the validation script is bulky.  Maybe this can be avoided using strongly typed parameters.  

## Possible Solution

        # Timezone (default: your local time)
        [System.TimeZoneInfo]
        $TimeZone = [System.TimeZoneInfo]::Local,

        # Specifies the system input locale and the keyboard layout (default: en-US)
        [Parameter(ValueFromPipelineByPropertyName)]
        [System.Globalization.CultureInfo]$InputLocale = [System.Globalization.CultureInfo]::GetCultureInfo('en-US'),

        # Specifies the language for non-Unicode programs (default: en-US)
        [Parameter(ValueFromPipelineByPropertyName)]
        [System.Globalization.CultureInfo]$SystemLocale = [System.Globalization.CultureInfo]::GetCultureInfo('en-US'),

        # Specifies the per-user settings used for formatting dates, times, currency and numbers (default: en-US)
        [Parameter(ValueFromPipelineByPropertyName)]
        [System.Globalization.CultureInfo]$UserLocale = [System.Globalization.CultureInfo]::GetCultureInfo('en-US'),

        # Specifies the system default user interface (UI) language (default: en-US)
        [System.Globalization.CultureInfo]$UILanguage = [System.Globalization.CultureInfo]::GetCultureInfo('en-US'),

Then the Id/Name property can be used in the unattended file.  

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Module version used:
* Operating System and PowerShell version:

**Comment by drstonephd** [comment]
I did not like using the non-string typed parameters.  This below might be the best of both worlds.  I use a trap because the methods called will fail if the time zone or culture is invalid.  The validation will still display the error.  

```
# Timezone (default: your local time zone)
[Parameter(ValueFromPipelineByPropertyName)]
[ValidateScript({
    trap [System.TimeZoneNotFoundException] {$false}
    [System.TimeZoneInfo]::FindSystemTimeZoneById($_) -ne $null
    })]
[string]
$TimeZone = [System.TimeZoneInfo]::Local.Id,

# Specifies the system input locale and the keyboard layout (default: en-US)
[Parameter(ValueFromPipelineByPropertyName)]
[ValidateScript({
    trap [System.Globalization.CultureNotFoundException] {$false}
    [System.Globalization.CultureInfo]::GetCultureInfo($_) -ne $null
    })]
[string]
$InputLocale = 'en-US',
```
BTW, The lists can be generated.  

```
[System.TimeZoneInfo]::GetSystemTimeZones().Id
[System.Globalization.CultureInfo]::GetCultures([System.Globalization.CultureTypes]::AllCultures).Name
```

**Comment by BladeFireLight** [comment]
The original reason for having the parameter sets was so it has tab completion. 
Based on your idea I found a way to use still have tab completion and not have to type them all out.

**Comment by drstonephd** [comment]
Looks like it's working.
